### ISSUE TITLE
Call external script

### ISSUE THREAD

**Issue by brantje** [captainhookbot/captain_hook#6]
```
services:   
  github:
    scripts:
        push:
          - /path/to/script.sh
```
Pass as 1st the event. As 2nd param the event data
